// Mocks generated by Mockito 5.4.6 from annotations
// in endurain/test/features/map/tracking_controls_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i12;

import 'package:endurain/core/models/activity.dart' as _i5;
import 'package:endurain/core/models/dynamic_map_zoom_preset.dart' as _i8;
import 'package:endurain/core/models/gps_filter_mode.dart' as _i4;
import 'package:endurain/core/models/route_display_mode.dart' as _i11;
import 'package:endurain/core/services/secure_storage_service.dart' as _i13;
import 'package:endurain/core/services/tracking_session_engine.dart' as _i2;
import 'package:endurain/core/theme/app_theme.dart' as _i10;
import 'package:endurain/features/settings/controllers/settings_controller.dart'
    as _i6;
import 'package:flutter/material.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTrackingSessionSnapshot_0 extends _i1.SmartFake
    implements _i2.TrackingSessionSnapshot {
  _FakeTrackingSessionSnapshot_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTrackingDiagnosticsSummary_1 extends _i1.SmartFake
    implements _i2.TrackingDiagnosticsSummary {
  _FakeTrackingDiagnosticsSummary_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TrackingSessionEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrackingSessionEngine extends _i1.Mock
    implements _i2.TrackingSessionEngine {
  MockTrackingSessionEngine() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TrackingSessionState get currentSessionState =>
      (super.noSuchMethod(
            Invocation.getter(#currentSessionState),
            returnValue: _i2.TrackingSessionState.idle,
          )
          as _i2.TrackingSessionState);

  @override
  _i2.TrackingSessionSnapshot get snapshot =>
      (super.noSuchMethod(
            Invocation.getter(#snapshot),
            returnValue: _FakeTrackingSessionSnapshot_0(
              this,
              Invocation.getter(#snapshot),
            ),
          )
          as _i2.TrackingSessionSnapshot);

  @override
  _i3.Stream<_i2.TrackingSessionSnapshot> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i3.Stream<_i2.TrackingSessionSnapshot>.empty(),
          )
          as _i3.Stream<_i2.TrackingSessionSnapshot>);

  @override
  _i2.TrackingDiagnosticsSummary get diagnosticsSummary =>
      (super.noSuchMethod(
            Invocation.getter(#diagnosticsSummary),
            returnValue: _FakeTrackingDiagnosticsSummary_1(
              this,
              Invocation.getter(#diagnosticsSummary),
            ),
          )
          as _i2.TrackingDiagnosticsSummary);

  @override
  List<Map<String, Object?>> get diagnosticsRecentEvents =>
      (super.noSuchMethod(
            Invocation.getter(#diagnosticsRecentEvents),
            returnValue: <Map<String, Object?>>[],
          )
          as List<Map<String, Object?>>);

  @override
  void setGpsFilterMode(_i4.GpsFilterMode? mode) => super.noSuchMethod(
    Invocation.method(#setGpsFilterMode, [mode]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<bool> start(
    _i5.ActivityType? activityType, {
    int? activityTypeId,
    DateTime? startedAt,
    bool? useCountdown = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #start,
              [activityType],
              {
                #activityTypeId: activityTypeId,
                #startedAt: startedAt,
                #useCountdown: useCountdown,
              },
            ),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> resume() =>
      (super.noSuchMethod(
            Invocation.method(#resume, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i5.Activity?> stop({DateTime? endedAt}) =>
      (super.noSuchMethod(
            Invocation.method(#stop, [], {#endedAt: endedAt}),
            returnValue: _i3.Future<_i5.Activity?>.value(),
          )
          as _i3.Future<_i5.Activity?>);

  @override
  _i3.Future<void> reset() =>
      (super.noSuchMethod(
            Invocation.method(#reset, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSavedActivity(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSavedActivity, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SettingsController].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsController extends _i1.Mock
    implements _i6.SettingsController {
  MockSettingsController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get version =>
      (super.noSuchMethod(
            Invocation.getter(#version),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#version),
            ),
          )
          as String);

  @override
  String get buildInfo =>
      (super.noSuchMethod(
            Invocation.getter(#buildInfo),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#buildInfo),
            ),
          )
          as String);

  @override
  String get copyright =>
      (super.noSuchMethod(
            Invocation.getter(#copyright),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#copyright),
            ),
          )
          as String);

  @override
  bool get audioEnabled =>
      (super.noSuchMethod(Invocation.getter(#audioEnabled), returnValue: false)
          as bool);

  @override
  double get voiceVolume =>
      (super.noSuchMethod(Invocation.getter(#voiceVolume), returnValue: 0.0)
          as double);

  @override
  bool get announceStart =>
      (super.noSuchMethod(Invocation.getter(#announceStart), returnValue: false)
          as bool);

  @override
  bool get announceSplits =>
      (super.noSuchMethod(
            Invocation.getter(#announceSplits),
            returnValue: false,
          )
          as bool);

  @override
  bool get announceGps =>
      (super.noSuchMethod(Invocation.getter(#announceGps), returnValue: false)
          as bool);

  @override
  bool get dynamicMapZoomEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#dynamicMapZoomEnabled),
            returnValue: false,
          )
          as bool);

  @override
  _i8.DynamicMapZoomPreset get dynamicMapZoomPreset =>
      (super.noSuchMethod(
            Invocation.getter(#dynamicMapZoomPreset),
            returnValue: _i8.DynamicMapZoomPreset.conservative,
          )
          as _i8.DynamicMapZoomPreset);

  @override
  _i9.ThemeMode get themeMode =>
      (super.noSuchMethod(
            Invocation.getter(#themeMode),
            returnValue: _i9.ThemeMode.system,
          )
          as _i9.ThemeMode);

  @override
  bool get highContrast =>
      (super.noSuchMethod(Invocation.getter(#highContrast), returnValue: false)
          as bool);

  @override
  _i10.AppThemePreset get themePreset =>
      (super.noSuchMethod(
            Invocation.getter(#themePreset),
            returnValue: _i10.AppThemePreset.ocean,
          )
          as _i10.AppThemePreset);

  @override
  _i11.RouteDisplayMode get routeDisplayMode =>
      (super.noSuchMethod(
            Invocation.getter(#routeDisplayMode),
            returnValue: _i11.RouteDisplayMode.auto,
          )
          as _i11.RouteDisplayMode);

  @override
  bool get ecoModeEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#ecoModeEnabled),
            returnValue: false,
          )
          as bool);

  @override
  _i4.GpsFilterMode get gpsFilterMode =>
      (super.noSuchMethod(
            Invocation.getter(#gpsFilterMode),
            returnValue: _i4.GpsFilterMode.auto,
          )
          as _i4.GpsFilterMode);

  @override
  bool get allowInsecureTls =>
      (super.noSuchMethod(
            Invocation.getter(#allowInsecureTls),
            returnValue: false,
          )
          as bool);

  @override
  bool get batteryOptimizationIgnored =>
      (super.noSuchMethod(
            Invocation.getter(#batteryOptimizationIgnored),
            returnValue: false,
          )
          as bool);

  @override
  bool get supportsBatteryOptimizationControl =>
      (super.noSuchMethod(
            Invocation.getter(#supportsBatteryOptimizationControl),
            returnValue: false,
          )
          as bool);

  @override
  bool get isUnlocked =>
      (super.noSuchMethod(Invocation.getter(#isUnlocked), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void unlock() => super.noSuchMethod(
    Invocation.method(#unlock, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> refreshAudioState({bool? notify = true}) =>
      (super.noSuchMethod(
            Invocation.method(#refreshAudioState, [], {#notify: notify}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setVoiceVolume(double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setVoiceVolume, [value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void toggleAudio(bool? value) => super.noSuchMethod(
    Invocation.method(#toggleAudio, [value]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> setAnnounceStart(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setAnnounceStart, [value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setAnnounceSplits(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setAnnounceSplits, [value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setAnnounceGps(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setAnnounceGps, [value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setThemeMode(_i9.ThemeMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setThemeMode, [mode]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setHighContrast(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setHighContrast, [enabled]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setThemePreset(_i10.AppThemePreset? preset) =>
      (super.noSuchMethod(
            Invocation.method(#setThemePreset, [preset]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setRouteDisplayMode(_i11.RouteDisplayMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setRouteDisplayMode, [mode]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setEcoMode(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setEcoMode, [enabled]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setGpsFilterMode(_i4.GpsFilterMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setGpsFilterMode, [mode]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setDynamicMapZoomEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setDynamicMapZoomEnabled, [enabled]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setDynamicMapZoomPreset(_i8.DynamicMapZoomPreset? preset) =>
      (super.noSuchMethod(
            Invocation.method(#setDynamicMapZoomPreset, [preset]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setAllowInsecureTls(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setAllowInsecureTls, [enabled]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> refreshBatteryOptimizationStatus({bool? notify = true}) =>
      (super.noSuchMethod(
            Invocation.method(#refreshBatteryOptimizationStatus, [], {
              #notify: notify,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> requestBatteryExemption() =>
      (super.noSuchMethod(
            Invocation.method(#requestBatteryExemption, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i13.SecureStorageService {
  MockSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> read({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {#key: key}),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> write({required String? key, required String? value}) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {#key: key, #value: value}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> delete({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {#key: key}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getServerUrl() =>
      (super.noSuchMethod(
            Invocation.method(#getServerUrl, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> setServerUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#setServerUrl, [url]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteServerUrl() =>
      (super.noSuchMethod(
            Invocation.method(#deleteServerUrl, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getUsername() =>
      (super.noSuchMethod(
            Invocation.method(#getUsername, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> setUsername(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#setUsername, [username]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteUsername() =>
      (super.noSuchMethod(
            Invocation.method(#deleteUsername, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getPassword() =>
      (super.noSuchMethod(
            Invocation.method(#getPassword, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> setPassword(String? password) =>
      (super.noSuchMethod(
            Invocation.method(#setPassword, [password]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deletePassword() =>
      (super.noSuchMethod(
            Invocation.method(#deletePassword, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getTileServerUrl() =>
      (super.noSuchMethod(
            Invocation.method(#getTileServerUrl, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> setTileServerUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#setTileServerUrl, [url]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTileServerUrl() =>
      (super.noSuchMethod(
            Invocation.method(#deleteTileServerUrl, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getTileServerAttribution() =>
      (super.noSuchMethod(
            Invocation.method(#getTileServerAttribution, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> setTileServerAttribution(String? attribution) =>
      (super.noSuchMethod(
            Invocation.method(#setTileServerAttribution, [attribution]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTileServerAttribution() =>
      (super.noSuchMethod(
            Invocation.method(#deleteTileServerAttribution, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getMapBackgroundColor() =>
      (super.noSuchMethod(
            Invocation.method(#getMapBackgroundColor, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> setMapBackgroundColor(String? color) =>
      (super.noSuchMethod(
            Invocation.method(#setMapBackgroundColor, [color]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> getEcoModeEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#getEcoModeEnabled, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> setEcoModeEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setEcoModeEnabled, [enabled]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteMapBackgroundColor() =>
      (super.noSuchMethod(
            Invocation.method(#deleteMapBackgroundColor, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> getAudioEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#getAudioEnabled, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> setAudioEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setAudioEnabled, [enabled]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<double?> getAudioVolume() =>
      (super.noSuchMethod(
            Invocation.method(#getAudioVolume, []),
            returnValue: _i3.Future<double?>.value(),
          )
          as _i3.Future<double?>);

  @override
  _i3.Future<void> setAudioVolume(double? volume) =>
      (super.noSuchMethod(
            Invocation.method(#setAudioVolume, [volume]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setLastLocation(double? lat, double? lng) =>
      (super.noSuchMethod(
            Invocation.method(#setLastLocation, [lat, lng]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<(double, double)?> getLastLocation() =>
      (super.noSuchMethod(
            Invocation.method(#getLastLocation, []),
            returnValue: _i3.Future<(double, double)?>.value(),
          )
          as _i3.Future<(double, double)?>);

  @override
  _i3.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<String?> getMetricConfig() =>
      (super.noSuchMethod(
            Invocation.method(#getMetricConfig, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> setMetricConfig(String? config) =>
      (super.noSuchMethod(
            Invocation.method(#setMetricConfig, [config]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setAccessToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#setAccessToken, [token]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccessToken, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> setRefreshToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#setRefreshToken, [token]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteRefreshToken, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getSessionId() =>
      (super.noSuchMethod(
            Invocation.method(#getSessionId, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> setSessionId(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#setSessionId, [sessionId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSessionId() =>
      (super.noSuchMethod(
            Invocation.method(#deleteSessionId, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getThemeMode() =>
      (super.noSuchMethod(
            Invocation.method(#getThemeMode, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> setThemeMode(String? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setThemeMode, [mode]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteThemeMode() =>
      (super.noSuchMethod(
            Invocation.method(#deleteThemeMode, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getThemePreset() =>
      (super.noSuchMethod(
            Invocation.method(#getThemePreset, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> setThemePreset(String? preset) =>
      (super.noSuchMethod(
            Invocation.method(#setThemePreset, [preset]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteThemePreset() =>
      (super.noSuchMethod(
            Invocation.method(#deleteThemePreset, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> getHighContrast() =>
      (super.noSuchMethod(
            Invocation.method(#getHighContrast, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> setHighContrast(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setHighContrast, [enabled]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteHighContrast() =>
      (super.noSuchMethod(
            Invocation.method(#deleteHighContrast, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> getMapMatchingPreviewEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#getMapMatchingPreviewEnabled, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> setMapMatchingPreviewEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setMapMatchingPreviewEnabled, [enabled]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteMapMatchingPreviewEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#deleteMapMatchingPreviewEnabled, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getRouteDisplayMode() =>
      (super.noSuchMethod(
            Invocation.method(#getRouteDisplayMode, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> setRouteDisplayMode(String? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setRouteDisplayMode, [mode]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteRouteDisplayMode() =>
      (super.noSuchMethod(
            Invocation.method(#deleteRouteDisplayMode, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getGpsFilterMode() =>
      (super.noSuchMethod(
            Invocation.method(#getGpsFilterMode, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> setGpsFilterMode(String? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setGpsFilterMode, [mode]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteGpsFilterMode() =>
      (super.noSuchMethod(
            Invocation.method(#deleteGpsFilterMode, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> getAllowInsecureTls() =>
      (super.noSuchMethod(
            Invocation.method(#getAllowInsecureTls, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> setAllowInsecureTls(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setAllowInsecureTls, [enabled]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAllowInsecureTls() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllowInsecureTls, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> clearAuthTokens() =>
      (super.noSuchMethod(
            Invocation.method(#clearAuthTokens, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> getPermissionsOnboardingCompleted() =>
      (super.noSuchMethod(
            Invocation.method(#getPermissionsOnboardingCompleted, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> setPermissionsOnboardingCompleted(bool? completed) =>
      (super.noSuchMethod(
            Invocation.method(#setPermissionsOnboardingCompleted, [completed]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deletePermissionsOnboardingCompleted() =>
      (super.noSuchMethod(
            Invocation.method(#deletePermissionsOnboardingCompleted, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
