// Mocks generated by Mockito 5.4.6 from annotations
// in endurain/test/core/services/tracking_session_engine_memory_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:endurain/core/models/activity.dart' as _i4;
import 'package:endurain/core/services/activity_repository.dart' as _i2;
import 'package:endurain/core/services/audio_feedback_service.dart' as _i5;
import 'package:endurain/core/services/bluetooth_sensor_service.dart' as _i6;
import 'package:endurain/core/services/location_service.dart' as _i8;
import 'package:flutter_blue_plus/flutter_blue_plus.dart' as _i7;
import 'package:geolocator/geolocator.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ActivityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivityRepository extends _i1.Mock
    implements _i2.ActivityRepository {
  MockActivityRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> create(_i4.Activity? activity) =>
      (super.noSuchMethod(
            Invocation.method(#create, [activity]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> update(_i4.Activity? activity) =>
      (super.noSuchMethod(
            Invocation.method(#update, [activity]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> insertTrackPoint(
    String? activityId,
    _i4.TrackPoint? point,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertTrackPoint, [activityId, point]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.Activity?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i3.Future<_i4.Activity?>.value(),
          )
          as _i3.Future<_i4.Activity?>);

  @override
  _i3.Future<_i4.Activity?> getSummaryById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSummaryById, [id]),
            returnValue: _i3.Future<_i4.Activity?>.value(),
          )
          as _i3.Future<_i4.Activity?>);

  @override
  _i3.Future<int> countTrackPoints(String? activityId) =>
      (super.noSuchMethod(
            Invocation.method(#countTrackPoints, [activityId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.TrackPoint>> getTrackPointsPage(
    String? activityId, {
    required int? limit,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getTrackPointsPage,
              [activityId],
              {#limit: limit, #offset: offset},
            ),
            returnValue: _i3.Future<List<_i4.TrackPoint>>.value(
              <_i4.TrackPoint>[],
            ),
          )
          as _i3.Future<List<_i4.TrackPoint>>);

  @override
  _i3.Future<List<_i4.Activity>> listAll() =>
      (super.noSuchMethod(
            Invocation.method(#listAll, []),
            returnValue: _i3.Future<List<_i4.Activity>>.value(<_i4.Activity>[]),
          )
          as _i3.Future<List<_i4.Activity>>);

  @override
  _i3.Stream<List<_i4.Activity>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i3.Stream<List<_i4.Activity>>.empty(),
          )
          as _i3.Stream<List<_i4.Activity>>);

  @override
  _i3.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [AudioFeedbackService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioFeedbackService extends _i1.Mock
    implements _i5.AudioFeedbackService {
  MockAudioFeedbackService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isEnabled =>
      (super.noSuchMethod(Invocation.getter(#isEnabled), returnValue: false)
          as bool);

  @override
  _i3.Stream<bool> get enabledStream =>
      (super.noSuchMethod(
            Invocation.getter(#enabledStream),
            returnValue: _i3.Stream<bool>.empty(),
          )
          as _i3.Stream<bool>);

  @override
  _i3.Future<void> setVolume(double? volume) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [volume]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateSettings({
    required bool? enabled,
    required bool? announceSplits,
    required bool? announceStart,
    bool? announceGps = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateSettings, [], {
              #enabled: enabled,
              #announceSplits: announceSplits,
              #announceStart: announceStart,
              #announceGps: announceGps,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void toggleEnabled(bool? enabled) => super.noSuchMethod(
    Invocation.method(#toggleEnabled, [enabled]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> speak(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#speak, [text]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setEnabledWithAnnouncement(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setEnabledWithAnnouncement, [enabled]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> announceCountdown(int? seconds) =>
      (super.noSuchMethod(
            Invocation.method(#announceCountdown, [seconds]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> announceStart() =>
      (super.noSuchMethod(
            Invocation.method(#announceStart, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> announceSplit({
    required int? km,
    required double? paceSecondsPerKm,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#announceSplit, [], {
              #km: km,
              #paceSecondsPerKm: paceSecondsPerKm,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> announceGpsStatus({required bool? isLost}) =>
      (super.noSuchMethod(
            Invocation.method(#announceGpsStatus, [], {#isLost: isLost}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [BluetoothSensorService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBluetoothSensorService extends _i1.Mock
    implements _i6.BluetoothSensorService {
  MockBluetoothSensorService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<int> get heartRate =>
      (super.noSuchMethod(
            Invocation.getter(#heartRate),
            returnValue: _i3.Stream<int>.empty(),
          )
          as _i3.Stream<int>);

  @override
  _i3.Stream<int> get cadence =>
      (super.noSuchMethod(
            Invocation.getter(#cadence),
            returnValue: _i3.Stream<int>.empty(),
          )
          as _i3.Stream<int>);

  @override
  _i3.Stream<List<_i7.ScanResult>> get scanResults =>
      (super.noSuchMethod(
            Invocation.getter(#scanResults),
            returnValue: _i3.Stream<List<_i7.ScanResult>>.empty(),
          )
          as _i3.Stream<List<_i7.ScanResult>>);

  @override
  _i3.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> startScan() =>
      (super.noSuchMethod(
            Invocation.method(#startScan, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stopScan() =>
      (super.noSuchMethod(
            Invocation.method(#stopScan, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> connect(_i7.BluetoothDevice? device) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [device]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> disconnect(_i7.BluetoothDevice? device) =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, [device]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i8.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setEcoMode(bool? enabled) => super.noSuchMethod(
    Invocation.method(#setEcoMode, [enabled]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<bool> isLocationServiceEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isLocationServiceEnabled, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i9.LocationPermission> checkPermission() =>
      (super.noSuchMethod(
            Invocation.method(#checkPermission, []),
            returnValue: _i3.Future<_i9.LocationPermission>.value(
              _i9.LocationPermission.denied,
            ),
          )
          as _i3.Future<_i9.LocationPermission>);

  @override
  _i3.Future<_i9.LocationPermission> requestPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, []),
            returnValue: _i3.Future<_i9.LocationPermission>.value(
              _i9.LocationPermission.denied,
            ),
          )
          as _i3.Future<_i9.LocationPermission>);

  @override
  _i3.Future<_i9.Position?> getLastKnownPosition() =>
      (super.noSuchMethod(
            Invocation.method(#getLastKnownPosition, []),
            returnValue: _i3.Future<_i9.Position?>.value(),
          )
          as _i3.Future<_i9.Position?>);

  @override
  _i3.Future<_i9.Position?> getCurrentPosition() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPosition, []),
            returnValue: _i3.Future<_i9.Position?>.value(),
          )
          as _i3.Future<_i9.Position?>);

  @override
  _i3.Stream<_i9.Position> getPositionStream() =>
      (super.noSuchMethod(
            Invocation.method(#getPositionStream, []),
            returnValue: _i3.Stream<_i9.Position>.empty(),
          )
          as _i3.Stream<_i9.Position>);

  @override
  _i3.Future<double?> getHeading() =>
      (super.noSuchMethod(
            Invocation.method(#getHeading, []),
            returnValue: _i3.Future<double?>.value(),
          )
          as _i3.Future<double?>);

  @override
  _i3.Future<bool> openAppSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openAppSettings, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
