import 'package:endurain/l10n/app_localizations.dart';

String localizeActivityTypeById(AppLocalizations l10n, int id) {
  switch (id) {
    case 1:
      return l10n.activityTypeRun;
    case 2:
      return l10n.activityTypeTrailRun;
    case 3:
      return l10n.activityTypeVirtualRun;
    case 4:
      return l10n.activityTypeRoadCycling;
    case 5:
      return l10n.activityTypeGravelCycling;
    case 6:
      return l10n.activityTypeMtbCycling;
    case 7:
      return l10n.activityTypeVirtualCycling;
    case 8:
      return l10n.activityTypeIndoorSwimming;
    case 9:
      return l10n.activityTypeOpenWaterSwimming;
    case 10:
      return l10n.activityTypeGeneralWorkout;
    case 11:
      return l10n.activityTypeWalk;
    case 12:
      return l10n.activityTypeHike;
    case 13:
      return l10n.activityTypeRowing;
    case 14:
      return l10n.activityTypeYoga;
    case 15:
      return l10n.activityTypeAlpineSki;
    case 16:
      return l10n.activityTypeNordicSki;
    case 17:
      return l10n.activityTypeSnowboard;
    case 18:
      return l10n.activityTypeTransition;
    case 19:
      return l10n.activityTypeStrengthTraining;
    case 20:
      return l10n.activityTypeCrossfit;
    case 21:
      return l10n.activityTypeTennis;
    case 22:
      return l10n.activityTypeTableTennis;
    case 23:
      return l10n.activityTypeBadminton;
    case 24:
      return l10n.activityTypeSquash;
    case 25:
      return l10n.activityTypeRacquetball;
    case 26:
      return l10n.activityTypePickleball;
    case 27:
      return l10n.activityTypeCommutingCycling;
    case 28:
      return l10n.activityTypeIndoorCycling;
    case 29:
      return l10n.activityTypeMixedSurfaceCycling;
    case 30:
      return l10n.activityTypeWindsurf;
    case 31:
      return l10n.activityTypeIndoorWalk;
    case 32:
      return l10n.activityTypeStandUpPaddling;
    case 33:
      return l10n.activityTypeSurf;
    case 34:
      return l10n.activityTypeTrackRun;
    case 35:
      return l10n.activityTypeEBikeCycling;
    case 36:
      return l10n.activityTypeEBikeMountainCycling;
    case 37:
      return l10n.activityTypeIceSkate;
    case 38:
      return l10n.activityTypeSoccer;
    case 39:
      return l10n.activityTypePadel;
    case 40:
      return l10n.activityTypeTreadmillRun;
    case 41:
      return l10n.activityTypeCardioTraining;
    case 42:
      return l10n.activityTypeKayaking;
    case 43:
      return l10n.activityTypeSailing;
    case 44:
      return l10n.activityTypeSnowShoeing;
    case 45:
      return l10n.activityTypeInlineSkating;
    case 46:
      return l10n.activityTypeHiit;
    default:
      return l10n.activityTypeRun;
  }
}
