// Mocks generated by Mockito 5.4.6 from annotations
// in endurain/test/features/auth/login_screen_di_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:endurain/core/error_handling/error_handler_service.dart' as _i6;
import 'package:endurain/core/models/identity_provider.dart' as _i3;
import 'package:endurain/features/auth/controllers/login_controller.dart'
    as _i2;
import 'package:flutter/material.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LoginController].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginController extends _i1.Mock implements _i2.LoginController {
  MockLoginController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isStep2 =>
      (super.noSuchMethod(Invocation.getter(#isStep2), returnValue: false)
          as bool);

  @override
  bool get showMfaInput =>
      (super.noSuchMethod(Invocation.getter(#showMfaInput), returnValue: false)
          as bool);

  @override
  bool get obscurePassword =>
      (super.noSuchMethod(
            Invocation.getter(#obscurePassword),
            returnValue: false,
          )
          as bool);

  @override
  bool get localLoginEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#localLoginEnabled),
            returnValue: false,
          )
          as bool);

  @override
  List<_i3.IdentityProvider> get availableIdPs =>
      (super.noSuchMethod(
            Invocation.getter(#availableIdPs),
            returnValue: <_i3.IdentityProvider>[],
          )
          as List<_i3.IdentityProvider>);

  @override
  bool get loginSuccess =>
      (super.noSuchMethod(Invocation.getter(#loginSuccess), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void togglePasswordVisibility() => super.noSuchMethod(
    Invocation.method(#togglePasswordVisibility, []),
    returnValueForMissingStub: null,
  );

  @override
  void resetStep2() => super.noSuchMethod(
    Invocation.method(#resetStep2, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> checkServerUrl(String? serverUrl) =>
      (super.noSuchMethod(
            Invocation.method(#checkServerUrl, [serverUrl]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> login(
    String? username,
    String? password,
    String? serverUrl,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password, serverUrl]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> verifyMfa(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#verifyMfa, [code]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> initiateSso(String? slug, String? serverUrl) =>
      (super.noSuchMethod(
            Invocation.method(#initiateSso, [slug, serverUrl]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> completeSso(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#completeSso, [sessionId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void handleSsoError(Object? error) => super.noSuchMethod(
    Invocation.method(#handleSsoError, [error]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ErrorHandlerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockErrorHandlerService extends _i1.Mock
    implements _i6.ErrorHandlerService {
  MockErrorHandlerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void showError({
    required _i7.BuildContext? context,
    required dynamic error,
    _i5.VoidCallback? onRetry,
    _i5.VoidCallback? onClose,
    bool? isCritical = true,
  }) => super.noSuchMethod(
    Invocation.method(#showError, [], {
      #context: context,
      #error: error,
      #onRetry: onRetry,
      #onClose: onClose,
      #isCritical: isCritical,
    }),
    returnValueForMissingStub: null,
  );
}
